trigger:
- main

pool:
  vmImage: mcr.microsoft.com/playwright:focal

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run test
  displayName: 'npm install and test'
